
services:
  pdf2zh:
    build: ./
    # image: byaidu/pdf2zh
    container_name: pdf2zh
    # env_file: .env
    restart: unless-stopped
    ports:
      - 7860:7860
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    # volumes:
    #   - ./data:/app/backend/data
    #   - ./memory:/app/backend/memory_jsons
    networks: 
      - net
networks: 
  net: {}
